package database

var TenantSystemRoles = []RoleSeed{
	{
		Name:        "impersonation_accessor",
		DisplayName: "提权访问者",
		Description: "平台管理员通过 Impersonation 进入租户时使用的角色，拥有管理员大部分权限但不能审批提权请求",
		IsSystem:    true,
		Scope:       "tenant",
		Permissions: []string{
			"user:list", "user:create", "user:update", "user:delete", "user:reset_password",
			"role:list", "role:create", "role:update", "role:delete", "role:assign",
			"plugin:list", "plugin:detail", "plugin:create", "plugin:update", "plugin:delete", "plugin:sync", "plugin:test",
			"secrets:query",
			"repository:list", "repository:create", "repository:update", "repository:delete", "repository:sync", "repository:validate",
			"playbook:list", "playbook:create", "playbook:update", "playbook:delete", "playbook:execute",
			"task:list", "task:detail", "task:create", "task:update", "task:delete", "task:cancel",
			"channel:list", "channel:create", "channel:update", "channel:delete",
			"template:list", "template:create", "template:update", "template:delete",
			"notification:list", "notification:send",
			"healing:flows:view", "healing:flows:create", "healing:flows:update", "healing:flows:delete",
			"healing:rules:view", "healing:rules:create", "healing:rules:update", "healing:rules:delete",
			"healing:instances:view",
			"healing:approvals:view", "healing:approvals:approve",
			"healing:trigger:view", "healing:trigger:execute",
			"dashboard:view", "dashboard:config:manage", "dashboard:workspace:manage",
			"site-message:list", "site-message:create", "site-message:settings:view", "site-message:settings:manage",
			"audit:list", "audit:export",
			"system:settings",
			"workflow:list", "workflow:detail", "workflow:create", "workflow:update", "workflow:delete", "workflow:activate", "workflow:run",
			"security:blacklist:view", "security:blacklist:create", "security:blacklist:update", "security:blacklist:delete",
			"security:exemption:view", "security:exemption:create", "security:exemption:approve",
		},
	},
	{
		Name:        "admin",
		DisplayName: "管理员",
		Description: "可管理用户、角色、插件、执行任务等核心资源",
		IsSystem:    true,
		Scope:       "tenant",
		Permissions: []string{
			"user:list", "user:create", "user:update", "user:delete", "user:reset_password",
			"role:list", "role:create", "role:update", "role:delete", "role:assign",
			"plugin:list", "plugin:detail", "plugin:create", "plugin:update", "plugin:delete", "plugin:sync", "plugin:test",
			"secrets:query",
			"repository:list", "repository:create", "repository:update", "repository:delete", "repository:sync", "repository:validate",
			"playbook:list", "playbook:create", "playbook:update", "playbook:delete", "playbook:execute",
			"task:list", "task:detail", "task:create", "task:update", "task:delete", "task:cancel",
			"channel:list", "channel:create", "channel:update", "channel:delete",
			"template:list", "template:create", "template:update", "template:delete",
			"notification:list", "notification:send",
			"healing:flows:view", "healing:flows:create", "healing:flows:update", "healing:flows:delete",
			"healing:rules:view", "healing:rules:create", "healing:rules:update", "healing:rules:delete",
			"healing:instances:view",
			"healing:approvals:view", "healing:approvals:approve",
			"healing:trigger:view", "healing:trigger:execute",
			"dashboard:view", "dashboard:config:manage", "dashboard:workspace:manage",
			"site-message:list", "site-message:create", "site-message:settings:view", "site-message:settings:manage",
			"audit:list", "audit:export",
			"system:settings",
			"workflow:list", "workflow:detail", "workflow:create", "workflow:update", "workflow:delete", "workflow:activate", "workflow:run",
			"tenant:impersonation:view", "tenant:impersonation:approve",
			"security:blacklist:view", "security:blacklist:create", "security:blacklist:update", "security:blacklist:delete",
			"security:exemption:view", "security:exemption:create", "security:exemption:approve",
		},
	},
	{
		Name:        "operator",
		DisplayName: "运维人员",
		Description: "可执行运维操作、管理自愈流程和查看系统信息",
		IsSystem:    true,
		Scope:       "tenant",
		Permissions: []string{
			"plugin:list", "plugin:detail", "plugin:sync", "plugin:test",
			"secrets:query",
			"repository:list", "repository:sync",
			"playbook:list", "playbook:execute",
			"task:list", "task:detail", "task:create", "task:update", "task:cancel",
			"channel:list", "template:list", "notification:list", "notification:send",
			"healing:flows:view", "healing:flows:create", "healing:flows:update",
			"healing:rules:view", "healing:rules:create", "healing:rules:update",
			"healing:instances:view",
			"healing:approvals:view", "healing:approvals:approve",
			"healing:trigger:view", "healing:trigger:execute",
			"dashboard:view",
			"site-message:list",
			"audit:list",
			"workflow:list", "workflow:detail", "workflow:update", "workflow:activate", "workflow:run",
			"tenant:impersonation:view",
			"security:blacklist:view", "security:blacklist:update",
			"security:exemption:view", "security:exemption:create",
		},
	},
	{
		Name:        "viewer",
		DisplayName: "只读用户",
		Description: "只能查看系统信息，不能进行任何修改操作",
		IsSystem:    true,
		Scope:       "tenant",
		Permissions: []string{
			"plugin:list", "plugin:detail",
			"repository:list", "playbook:list", "task:list", "task:detail",
			"channel:list", "template:list", "notification:list",
			"healing:flows:view", "healing:rules:view", "healing:instances:view",
			"healing:approvals:view", "healing:trigger:view",
			"dashboard:view",
			"site-message:list",
			"audit:list",
			"workflow:list", "workflow:detail",
			"tenant:impersonation:view",
			"security:blacklist:view",
			"security:exemption:view",
		},
	},
	{
		Name:        "healing_engineer",
		DisplayName: "自愈工程师",
		Description: "专注自愈流程的设计和运维，可管理流程、规则、审批和触发，其他模块只读",
		IsSystem:    true,
		Scope:       "tenant",
		Permissions: []string{
			"healing:flows:view", "healing:flows:create", "healing:flows:update", "healing:flows:delete",
			"healing:rules:view", "healing:rules:create", "healing:rules:update", "healing:rules:delete",
			"healing:instances:view",
			"healing:approvals:view", "healing:approvals:approve",
			"healing:trigger:view", "healing:trigger:execute",
			"task:list", "task:detail",
			"repository:list",
			"playbook:list", "playbook:execute",
			"plugin:list", "plugin:detail", "plugin:sync", "plugin:test",
			"channel:list", "template:list", "notification:list",
			"dashboard:view",
			"site-message:list",
			"audit:list",
			"workflow:list", "workflow:detail",
		},
	},
	{
		Name:        "devops_engineer",
		DisplayName: "运维工程师",
		Description: "专注任务执行和自动化运维，可管理执行任务、Playbook和Git仓库，其他模块只读",
		IsSystem:    true,
		Scope:       "tenant",
		Permissions: []string{
			"task:list", "task:detail", "task:create", "task:update", "task:delete", "task:cancel",
			"repository:list", "repository:create", "repository:update", "repository:delete", "repository:sync", "repository:validate",
			"playbook:list", "playbook:create", "playbook:update", "playbook:delete", "playbook:execute",
			"plugin:list", "plugin:detail", "plugin:sync", "plugin:test",
			"secrets:query",
			"healing:flows:view", "healing:rules:view", "healing:instances:view",
			"healing:approvals:view", "healing:trigger:view", "healing:trigger:execute",
			"channel:list", "template:list", "notification:list",
			"dashboard:view",
			"site-message:list",
			"audit:list",
			"workflow:list", "workflow:detail", "workflow:update", "workflow:activate", "workflow:run",
		},
	},
	{
		Name:        "notification_manager",
		DisplayName: "通知管理员",
		Description: "管理通知渠道、模板和站内信，可创建和发送通知，其他模块只读",
		IsSystem:    true,
		Scope:       "tenant",
		Permissions: []string{
			"channel:list", "channel:create", "channel:update", "channel:delete",
			"template:list", "template:create", "template:update", "template:delete",
			"notification:list", "notification:send",
			"site-message:list", "site-message:create", "site-message:settings:view", "site-message:settings:manage",
			"plugin:list", "plugin:detail",
			"task:list", "task:detail", "repository:list", "playbook:list",
			"healing:flows:view", "healing:rules:view", "healing:instances:view",
			"healing:approvals:view", "healing:trigger:view",
			"dashboard:view",
			"audit:list",
			"workflow:list", "workflow:detail",
		},
	},
	{
		Name:        "monitor_admin",
		DisplayName: "监控管理员",
		Description: "管理监控插件和Dashboard面板，可配置数据源和面板布局，其他模块只读",
		IsSystem:    true,
		Scope:       "tenant",
		Permissions: []string{
			"plugin:list", "plugin:detail", "plugin:create", "plugin:update", "plugin:delete", "plugin:sync", "plugin:test",
			"dashboard:view", "dashboard:config:manage", "dashboard:workspace:manage",
			"task:list", "task:detail", "repository:list", "playbook:list",
			"channel:list", "template:list", "notification:list",
			"healing:flows:view", "healing:rules:view", "healing:instances:view",
			"healing:approvals:view", "healing:trigger:view",
			"site-message:list",
			"audit:list",
			"workflow:list", "workflow:detail",
		},
	},
	{
		Name:        "auditor",
		DisplayName: "审计员",
		Description: "租户安全审计，可查看和导出审计日志，所有业务模块只读",
		IsSystem:    true,
		Scope:       "tenant",
		Permissions: []string{
			"audit:list", "audit:export",
			"plugin:list", "plugin:detail",
			"task:list", "task:detail", "repository:list", "playbook:list",
			"channel:list", "template:list", "notification:list",
			"healing:flows:view", "healing:rules:view", "healing:instances:view",
			"healing:approvals:view", "healing:trigger:view",
			"dashboard:view",
			"site-message:list",
			"workflow:list", "workflow:detail",
		},
	},
}
