package httpapi

import (
	"github.com/company/auto-healing/internal/middleware"
	"github.com/gin-gonic/gin"
)

func (r Registrar) RegisterTenantRoutes(tenant *gin.RouterGroup) {
	incidents := tenant.Group("/incidents")
	incidents.POST("/:id/trigger", middleware.RequirePermission("healing:trigger:execute"), r.deps.Healing.TriggerIncidentManually)
	incidents.POST("/:id/dismiss", middleware.RequirePermission("healing:trigger:execute"), r.deps.Healing.DismissIncident)

	tasks := tenant.Group("/execution-tasks")
	tasks.GET("", middleware.RequirePermission("task:list"), r.deps.Execution.ListTasks)
	tasks.POST("", middleware.RequirePermission("task:create"), r.deps.Execution.CreateTask)
	tasks.GET("/stats", middleware.RequirePermission("task:list"), r.deps.Execution.GetTaskStats)
	tasks.GET("/search-schema", middleware.RequirePermission("task:list"), r.deps.Execution.GetTaskSearchSchema)
	tasks.POST("/batch-confirm-review", middleware.RequirePermission("task:update"), r.deps.Execution.BatchConfirmReview)
	tasks.GET("/:id", middleware.RequirePermission("task:detail"), r.deps.Execution.GetTask)
	tasks.PUT("/:id", middleware.RequirePermission("task:update"), r.deps.Execution.UpdateTask)
	tasks.DELETE("/:id", middleware.RequirePermission("task:delete"), r.deps.Execution.DeleteTask)
	tasks.POST("/:id/execute", middleware.RequirePermission("playbook:execute"), r.deps.Execution.ExecuteTask)
	tasks.POST("/:id/confirm-review", middleware.RequirePermission("task:update"), r.deps.Execution.ConfirmReview)
	tasks.GET("/:id/runs", middleware.RequirePermission("task:detail"), r.deps.Execution.ListRuns)

	runs := tenant.Group("/execution-runs")
	runs.GET("", middleware.RequirePermission("task:list"), r.deps.Execution.ListAllRuns)
	runs.GET("/stats", middleware.RequirePermission("task:list"), r.deps.Execution.GetRunStats)
	runs.GET("/search-schema", middleware.RequirePermission("task:list"), r.deps.Execution.GetRunSearchSchema)
	runs.GET("/trend", middleware.RequirePermission("task:list"), r.deps.Execution.GetRunTrend)
	runs.GET("/trigger-distribution", middleware.RequirePermission("task:list"), r.deps.Execution.GetTriggerDistribution)
	runs.GET("/top-failed", middleware.RequirePermission("task:list"), r.deps.Execution.GetTopFailedTasks)
	runs.GET("/top-active", middleware.RequirePermission("task:list"), r.deps.Execution.GetTopActiveTasks)
	runs.GET("/:id", middleware.RequirePermission("task:detail"), r.deps.Execution.GetRun)
	runs.GET("/:id/logs", middleware.RequirePermission("task:detail"), r.deps.Execution.GetRunLogs)
	runs.GET("/:id/stream", middleware.RequirePermission("task:detail"), r.deps.Execution.StreamLogs)
	runs.POST("/:id/cancel", middleware.RequirePermission("task:cancel"), r.deps.Execution.CancelRun)

	schedules := tenant.Group("/execution-schedules")
	schedules.GET("", middleware.RequirePermission("task:list"), r.deps.Schedule.List)
	schedules.POST("", middleware.RequirePermission("task:create"), r.deps.Schedule.Create)
	schedules.GET("/stats", middleware.RequirePermission("task:list"), r.deps.Schedule.GetStats)
	schedules.GET("/timeline", middleware.RequirePermission("task:list"), r.deps.Schedule.GetTimeline)
	schedules.GET("/:id", middleware.RequirePermission("task:detail"), r.deps.Schedule.Get)
	schedules.PUT("/:id", middleware.RequirePermission("task:update"), r.deps.Schedule.Update)
	schedules.DELETE("/:id", middleware.RequirePermission("task:delete"), r.deps.Schedule.Delete)
	schedules.POST("/:id/enable", middleware.RequirePermission("task:update"), r.deps.Schedule.Enable)
	schedules.POST("/:id/disable", middleware.RequirePermission("task:update"), r.deps.Schedule.Disable)

	flows := tenant.Group("/healing/flows")
	flows.GET("/node-schema", middleware.RequirePermission("healing:flows:view"), r.deps.Healing.GetNodeSchema)
	flows.GET("/search-schema", middleware.RequirePermission("healing:flows:view"), r.deps.Healing.GetFlowSearchSchema)
	flows.GET("", middleware.RequirePermission("healing:flows:view"), r.deps.Healing.ListFlows)
	flows.POST("", middleware.RequirePermission("healing:flows:create"), r.deps.Healing.CreateFlow)
	flows.GET("/stats", middleware.RequirePermission("healing:flows:view"), r.deps.Healing.GetFlowStats)
	flows.GET("/:id", middleware.RequirePermission("healing:flows:view"), r.deps.Healing.GetFlow)
	flows.PUT("/:id", middleware.RequirePermission("healing:flows:update"), r.deps.Healing.UpdateFlow)
	flows.DELETE("/:id", middleware.RequirePermission("healing:flows:delete"), r.deps.Healing.DeleteFlow)
	flows.POST("/:id/dry-run", middleware.RequirePermission("healing:flows:update"), r.deps.Healing.DryRunFlow)
	flows.POST("/:id/dry-run-stream", middleware.RequirePermission("healing:flows:update"), r.deps.Healing.DryRunFlowStream)

	rules := tenant.Group("/healing/rules")
	rules.GET("/search-schema", middleware.RequirePermission("healing:rules:view"), r.deps.Healing.GetRuleSearchSchema)
	rules.GET("", middleware.RequirePermission("healing:rules:view"), r.deps.Healing.ListRules)
	rules.POST("", middleware.RequirePermission("healing:rules:create"), r.deps.Healing.CreateRule)
	rules.GET("/stats", middleware.RequirePermission("healing:rules:view"), r.deps.Healing.GetRuleStats)
	rules.GET("/:id", middleware.RequirePermission("healing:rules:view"), r.deps.Healing.GetRule)
	rules.PUT("/:id", middleware.RequirePermission("healing:rules:update"), r.deps.Healing.UpdateRule)
	rules.DELETE("/:id", middleware.RequirePermission("healing:rules:delete"), r.deps.Healing.DeleteRule)
	rules.POST("/:id/activate", middleware.RequirePermission("healing:rules:update"), r.deps.Healing.ActivateRule)
	rules.POST("/:id/deactivate", middleware.RequirePermission("healing:rules:update"), r.deps.Healing.DeactivateRule)

	instances := tenant.Group("/healing/instances")
	instances.GET("/search-schema", middleware.RequirePermission("healing:instances:view"), r.deps.Healing.GetInstanceSearchSchema)
	instances.GET("", middleware.RequirePermission("healing:instances:view"), r.deps.Healing.ListInstances)
	instances.GET("/stats", middleware.RequirePermission("healing:instances:view"), r.deps.Healing.GetInstanceStats)
	instances.GET("/:id", middleware.RequirePermission("healing:instances:view"), r.deps.Healing.GetInstance)
	instances.GET("/:id/recovery-logs", middleware.RequirePermission("healing:instances:view"), r.deps.Healing.ListInstanceRecoveryAttempts)
	instances.POST("/:id/cancel", middleware.RequirePermission("healing:flows:update"), r.deps.Healing.CancelInstance)
	instances.POST("/:id/recover", middleware.RequirePermission("healing:flows:update"), r.deps.Healing.RecoverInstance)
	instances.POST("/:id/retry", middleware.RequirePermission("healing:flows:update"), r.deps.Healing.RetryInstance)
	instances.GET("/:id/events", middleware.RequirePermission("healing:instances:view"), r.deps.Healing.InstanceEvents)

	approvals := tenant.Group("/healing/approvals")
	approvals.GET("", middleware.RequirePermission("healing:approvals:view"), r.deps.Healing.ListApprovals)
	approvals.GET("/pending", middleware.RequirePermission("healing:approvals:view"), r.deps.Healing.ListPendingApprovals)
	approvals.GET("/:id", middleware.RequirePermission("healing:approvals:view"), r.deps.Healing.GetApproval)
	approvals.POST("/:id/approve", middleware.RequirePermission("healing:approvals:approve"), r.deps.Healing.ApproveTask)
	approvals.POST("/:id/reject", middleware.RequirePermission("healing:approvals:approve"), r.deps.Healing.RejectTask)

	pending := tenant.Group("/healing/pending")
	pending.GET("/trigger", middleware.RequirePermission("healing:trigger:view"), r.deps.Healing.ListPendingTriggerIncidents)
	pending.GET("/dismissed", middleware.RequirePermission("healing:trigger:view"), r.deps.Healing.ListDismissedTriggerIncidents)
}
