package httpapi

import (
	"github.com/company/auto-healing/internal/middleware"
	"github.com/gin-gonic/gin"
)

func (r Registrar) RegisterTenantRoutes(tenant *gin.RouterGroup) {
	plugins := tenant.Group("/plugins")
	plugins.GET("", middleware.RequirePermission("plugin:list"), r.deps.Plugin.ListPlugins)
	plugins.GET("/stats", middleware.RequirePermission("plugin:list"), r.deps.Plugin.GetPluginStats)
	plugins.GET("/search-schema", middleware.RequirePermission("plugin:list"), r.deps.Plugin.GetPluginSearchSchema)
	plugins.POST("", middleware.RequirePermission("plugin:create"), r.deps.Plugin.CreatePlugin)
	plugins.GET("/:id", middleware.RequirePermission("plugin:detail"), r.deps.Plugin.GetPlugin)
	plugins.PUT("/:id", middleware.RequirePermission("plugin:update"), r.deps.Plugin.UpdatePlugin)
	plugins.DELETE("/:id", middleware.RequirePermission("plugin:delete"), r.deps.Plugin.DeletePlugin)
	plugins.POST("/:id/test", middleware.RequirePermission("plugin:test"), r.deps.Plugin.TestPlugin)
	plugins.POST("/:id/activate", middleware.RequirePermission("plugin:update"), r.deps.Plugin.ActivatePlugin)
	plugins.POST("/:id/deactivate", middleware.RequirePermission("plugin:update"), r.deps.Plugin.DeactivatePlugin)
	plugins.POST("/:id/sync", middleware.RequirePermission("plugin:sync"), r.deps.Plugin.SyncPlugin)
	plugins.GET("/:id/logs", middleware.RequirePermission("plugin:list"), r.deps.Plugin.GetPluginSyncLogs)

	incidents := tenant.Group("/incidents")
	incidents.GET("/stats", middleware.RequirePermission("plugin:list"), r.deps.Plugin.GetIncidentStats)
	incidents.GET("/search-schema", middleware.RequirePermission("plugin:list"), r.deps.Plugin.GetIncidentSearchSchema)
	incidents.GET("", middleware.RequirePermission("plugin:list"), r.deps.Plugin.ListIncidents)
	incidents.POST("/batch-reset-scan", middleware.RequirePermission("plugin:sync"), r.deps.Plugin.BatchResetIncidentScan)
	incidents.GET("/:id", middleware.RequirePermission("plugin:list"), r.deps.Plugin.GetIncident)
	incidents.GET("/:id/writeback-logs", middleware.RequirePermission("plugin:list"), r.deps.Plugin.ListIncidentWritebackLogs)
	incidents.POST("/:id/reset-scan", middleware.RequirePermission("plugin:sync"), r.deps.Plugin.ResetIncidentScan)
	incidents.POST("/:id/close", middleware.RequirePermission("plugin:sync"), r.deps.Plugin.CloseIncident)

	cmdb := tenant.Group("/cmdb")
	cmdb.GET("", middleware.RequirePermission("plugin:list"), r.deps.CMDB.ListCMDBItems)
	cmdb.GET("/stats", middleware.RequirePermission("plugin:list"), r.deps.CMDB.GetCMDBStats)
	cmdb.GET("/search-schema", middleware.RequirePermission("plugin:list"), r.deps.CMDB.GetCMDBSearchSchema)
	cmdb.POST("/batch-test-connection", middleware.RequirePermission("plugin:sync"), r.deps.CMDB.BatchTestConnection)
	cmdb.POST("/batch/maintenance", middleware.RequirePermission("plugin:update"), r.deps.CMDB.BatchEnterMaintenance)
	cmdb.POST("/batch/resume", middleware.RequirePermission("plugin:update"), r.deps.CMDB.BatchExitMaintenance)
	cmdb.GET("/ids", middleware.RequirePermission("plugin:list"), r.deps.CMDB.ListCMDBItemIDs)
	cmdb.GET("/:id", middleware.RequirePermission("plugin:list"), r.deps.CMDB.GetCMDBItem)
	cmdb.POST("/:id/test-connection", middleware.RequirePermission("plugin:sync"), r.deps.CMDB.TestConnection)
	cmdb.POST("/:id/maintenance", middleware.RequirePermission("plugin:update"), r.deps.CMDB.EnterMaintenance)
	cmdb.POST("/:id/resume", middleware.RequirePermission("plugin:update"), r.deps.CMDB.ExitMaintenance)
	cmdb.GET("/:id/maintenance-logs", middleware.RequirePermission("plugin:list"), r.deps.CMDB.GetMaintenanceLogs)

	repos := tenant.Group("/git-repos")
	repos.POST("/validate", middleware.RequirePermission("repository:validate"), r.deps.GitRepo.ValidateRepo)
	repos.GET("", middleware.RequirePermission("repository:list"), r.deps.GitRepo.ListRepos)
	repos.POST("", middleware.RequireAllPermissions("repository:create", "repository:validate"), r.deps.GitRepo.CreateRepo)
	repos.GET("/stats", middleware.RequirePermission("repository:list"), r.deps.GitRepo.GetStats)
	repos.GET("/search-schema", middleware.RequirePermission("repository:list"), r.deps.GitRepo.GetSearchSchema)
	repos.GET("/:id", middleware.RequirePermission("repository:list"), r.deps.GitRepo.GetRepo)
	repos.PUT("/:id", middleware.RequirePermission("repository:update"), r.deps.GitRepo.UpdateRepo)
	repos.DELETE("/:id", middleware.RequirePermission("repository:delete"), r.deps.GitRepo.DeleteRepo)
	repos.POST("/:id/sync", middleware.RequirePermission("repository:sync"), r.deps.GitRepo.SyncRepo)
	repos.POST("/:id/reset-status", middleware.RequirePermission("repository:update"), r.deps.GitRepo.ResetStatus)
	repos.GET("/:id/logs", middleware.RequirePermission("repository:list"), r.deps.GitRepo.GetSyncLogs)
	repos.GET("/:id/commits", middleware.RequirePermission("repository:list"), r.deps.GitRepo.GetCommits)
	repos.GET("/:id/files", middleware.RequirePermission("repository:list"), r.deps.GitRepo.GetFiles)

	playbooks := tenant.Group("/playbooks")
	playbooks.GET("", middleware.RequirePermission("playbook:list"), r.deps.Playbook.List)
	playbooks.POST("", middleware.RequirePermission("playbook:create"), r.deps.Playbook.Create)
	playbooks.GET("/stats", middleware.RequirePermission("playbook:list"), r.deps.Playbook.GetStats)
	playbooks.GET("/:id", middleware.RequirePermission("playbook:list"), r.deps.Playbook.Get)
	playbooks.PUT("/:id", middleware.RequirePermission("playbook:update"), r.deps.Playbook.Update)
	playbooks.DELETE("/:id", middleware.RequirePermission("playbook:delete"), r.deps.Playbook.Delete)
	playbooks.POST("/:id/scan", middleware.RequirePermission("playbook:update"), r.deps.Playbook.ScanVariables)
	playbooks.PUT("/:id/variables", middleware.RequirePermission("playbook:update"), r.deps.Playbook.UpdateVariables)
	playbooks.POST("/:id/ready", middleware.RequirePermission("playbook:update"), r.deps.Playbook.SetReady)
	playbooks.POST("/:id/offline", middleware.RequirePermission("playbook:update"), r.deps.Playbook.SetOffline)
	playbooks.GET("/:id/files", middleware.RequirePermission("playbook:list"), r.deps.Playbook.GetFiles)
	playbooks.GET("/:id/scan-logs", middleware.RequirePermission("playbook:list"), r.deps.Playbook.GetScanLogs)
}
